### ISSUE TITLE
initWasmAsm doesn't seem to init ASM at all

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/wasm#315]
Split from https://github.com/polkadot-js/common/issues/1440

**Comment by jacogr** [comment]
Have no idea how it gets there, this is how it is checked -

https://github.com/polkadot-js/wasm/blob/eb445e79e2e12f5a638e49ebf18b462a1ceadfb7/packages/wasm-crypto/src/init.ts#L19-L29

This is where it is set -

https://github.com/polkadot-js/wasm/blob/eb445e79e2e12f5a638e49ebf18b462a1ceadfb7/packages/wasm-crypto/src/initWasmAsm.ts#L9

So it certainly passes asm.js through

**Comment by jacogr** [comment]
Logged some more in the ASM testcases and it does go through the asm path, so something is very whacky.

**Comment by jacogr** [comment]
@Tbaut Could you please check the latest beta of this and see if the problem persist?

Also would like to see some code to see where you add the import. (In needs to be before e.g. `cryptoWaitReady`, which actually gets auto-applied)

At this point my guess is that (for some reason) the code doesn't execute first. (And it certainly should work, logged the living daylights out of it in the tests, and it is used there...)

**Comment by Tbaut** [comment]
Sure, so the global import was made here:
https://github.com/Tbaut/RN-Test-Project/blob/main/App.tsx#L3

And anything I played with or logged like right now the `Identicon` is lower in the tree in `/screens/TabOneScreen` here:
https://github.com/Tbaut/RN-Test-Project/blob/main/screens/TabOneScreen.tsx#L6

I've added the wasm-crypto [5.0.2-3](https://www.npmjs.com/package/@polkadot/wasm-crypto/v/5.0.2-3) and get 

```
FATAL: Unable to initialize @polkadot/wasm-crypto
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:35:11 in createPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:43:38 in setPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bundle.cjs:201:21 in waitReady
at node_modules/@polkadot/util-crypto/crypto.cjs:18:27 in cryptoWaitReady
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208585:30 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208224:13 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208135:27 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208039:31 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:207937:53 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:207877:64 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:193220:56 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:7:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259835:3 in global code

WebAssembly is not available in your environment
at node_modules/@polkadot/util/assert.cjs:37:10 in assert
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:23:0 in createPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:43:38 in setPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bundle.cjs:201:21 in waitReady
at node_modules/@polkadot/util-crypto/crypto.cjs:18:27 in cryptoWaitReady
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208585:30 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208224:13 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208135:27 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:208039:31 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:207937:53 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:207877:64 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:193220:56 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:7:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259835:3 in global code

Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259835:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by jacogr** [comment]
Ok, the reason why I asked for the beta was that it also exposes the actual auto-called function to init now for testing... So in addition to the above ...

```js
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { initWasm } from '@polkadot/wasm-crypto/initOnlyAsm';

import useCachedResources from './hooks/useCachedResources';
import useColorScheme from './hooks/useColorScheme';
import Navigation from './navigation';

initWasm().catch(console.error);

export default function App() {
  const isLoadingComplete = useCachedResources();
  ...
```

Not great since that actual added call happens in the imported file, but let's try...

**Comment by Tbaut** [comment]
I added that [here](https://github.com/Tbaut/RN-Test-Project/commit/39a0d01655f5fae4b4baf937aeb4904511b6d790).
I'll paste the answer in case I miss something, but it looks like the same error to me

```
FATAL: Unable to initialize @polkadot/wasm-crypto
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:35:11 in createPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:43:38 in setPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bundle.cjs:201:21 in waitReady
at node_modules/@polkadot/util-crypto/crypto.cjs:18:27 in cryptoWaitReady
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162668:30 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162307:13 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162089:27 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:161993:31 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:153786:53 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:153726:64 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:139069:56 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259837:3 in global code

WebAssembly is not available in your environment
at node_modules/@polkadot/util/assert.cjs:36:18 in assert
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:23:0 in createPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:43:38 in setPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bundle.cjs:201:21 in waitReady
at node_modules/@polkadot/util-crypto/crypto.cjs:18:27 in cryptoWaitReady
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162668:30 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162307:13 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:162089:27 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:161993:31 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:153786:53 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:153726:64 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:139069:56 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259837:3 in global code

Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.178.72:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:259837:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

```

**Comment by jacogr** [comment]
The above error stack looks wrong. It is supposed to log only once instead of twice. Not sure it is updated?

https://github.com/polkadot-js/wasm/blob/7fb8a1cb93e1abb905af8e79fe1b0bfecb425cbf/packages/wasm-crypto/src/init.ts#L24

**Comment by Tbaut** [comment]
Indeed there's something I must be missing. I can definitely see the line you've pointed out in the `node_modules`, I've been cleaning cache etc as explained [in the doc](https://docs.expo.dev/troubleshooting/clear-cache-macos-linux/#expo-cli-and-yarn), but I still can't get that error with the `::`. I've even tried to eject uninstall the app.. I didn't find a way to inspect the bundle either. I'm out of idea and search keywords for now. No clue where this cached version comes from. I'll continue digging later today or tomorrow

**Comment by jacogr** [comment]
Try adding a yarn resolution to your package.json. That should ensure there is only 1 version. Something like -

```
"resolutions": {
    "@polkadot/wasm-crypto": "^5.0.2-3"
 }
 ```
 
 And then run `yarn` again. That should fix it.

**Comment by Tbaut** [comment]
Good call, searching for the error message was yielding only 1 match so I didn't think of this. Here's the new error message
```

FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:32:11 in createPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/init.cjs:42:46 in setPromise
at node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bundle.cjs:191:21 in waitReady
at node_modules/@polkadot/util-crypto/crypto.cjs:18:27 in cryptoWaitReady
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:162668:30 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:162307:13 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:162089:27 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:161993:31 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:153786:53 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:153726:64 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:139069:56 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:259827:3 in global code

Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.2.4:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:259827:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

```

**Comment by jacogr** [comment]
Something is seriously weird, it tries to call before the init is completed. And worse is that I can't even see any calls, i.e usage of any of this stuff. (Your screen with the icon doesn't seem linked?)

Have you tries `import '@polkadot/wasm-crypto/initOnlyAsm'` as the very first line? (in-case navigation does already start loading stuff)

Something is missing somewhere... feels like my mind...

**Comment by Tbaut** [comment]
I've removed the Navigation and anything around. 
This code shows the Hello text and all the `console.log`.

if I uncomment the `Identicon` (both in the code and the import), I get the error, and no log.

```js
import { initWasm } from '@polkadot/wasm-crypto/initOnlyAsm'
console.log('first')
initWasm().catch(console.error);

import { View, Text } from 'react-native'
// import Identicon from '@polkadot/reactnative-identicon';

export default function App() {
  console.log('body of App())')

  return (
    <View>
      <Text>Hello</Text>
      {/* <Identicon
        value="5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        size={48}
      /> */}
    </View>
  );
```

**Comment by jacogr** [comment]
I'll try again to get the RN environment setup locally. Last 3 tries ended up in tears, the one before that worked...

**Comment by jacogr** [comment]
It literally took me a full day & Googling like a madman since I'm "lucky" to have an M1, just to get just the environment setup. 

But I'm no further, 

`TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[5], "@polkadot/util-crypto").cryptoWaitReady')`

aka have not been able to get imports running, let alone WASM (`@polkadot/util` seems ok)

**Comment by jacogr** [comment]
I believe I fixed it in https://github.com/polkadot-js/wasm/pull/319 - it works for me now and a blake2 hash shows up on-screen after init. (It could be a combination of the wasm PR and https://github.com/polkadot-js/common/pull/1445 - both are  in the test project, along with the required `cryptoWaitReady()`)

**Comment by jacogr** [comment]
Closing. Cannot replicate in `@polkadot/wasm-crypto 5.1.1` & `@polkadot/util-crypto 8.7.1`.

**Comment by Tbaut** [comment]
Sounds good to me as well, the "WebAssembly is not available in your environment" error is gone

**Comment by Tbaut** [comment]
I may have spoken too soon, with the following code https://github.com/Tbaut/RN-Test-Project/blob/main/App.tsx and resolutions https://github.com/Tbaut/RN-Test-Project/blob/main/package.json#L49-L51 I get

```
Android Running app on Android SDK built for x86

FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment
at node_modules/@polkadot/wasm-crypto/init.cjs:37:6 in createPromise
at node_modules/@polkadot/wasm-crypto/init.cjs:44:46 in setWasmPromise
at node_modules/@polkadot/wasm-crypto/bundle.cjs:198:37 in waitReady
at App.tsx:8:2 in App
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:58:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication

The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
at node_modules/@polkadot/util/assert.cjs:37:10 in assert
at node_modules/@polkadot/wasm-crypto/bridge.cjs:36:4 in <anonymous>
at App.tsx:8:37 in waitReady.then$argument_0

```

**Comment by jacogr** [comment]
Doing -

```js
useEffect((): void => {
    waitReady()
      .then(() => setResult(bip39Generate(12)))
      .catch(console.error);
  }, []);
```

I did ensure I reset the cache when starting via `watchman watch-del-all && react-native start --reset-cache` (I actually changed my start command to that for test of this stuff)
  
![image](https://user-images.githubusercontent.com/1424473/160294658-35768dd4-3117-4f49-ba09-61e1acd44000.png)

**Comment by Tbaut** [comment]
My test project is still using a metro server and expo, and I reset all the cache I can as per the doc as well
```
rm -rf node_modules 
yarn cache clean
yarn
watchman watch-del-all
rm -fr /tmp/haste-map-*
rm -rf /tmp/metro-cache
expo start --clear
```

And the `useEffect` did not change the outcome unfortunately. I'll try by ejecting it to see if there's a change there

edit: no luck with an ejected version either.

**Comment by jacogr** [comment]
Will re-open, however I'm once again stuck where I can run my "metro project" but the above "expo project" just doesn't even run for me. So I certainly cannot replicate the issue anymore in _my_ environment, but also have no luck even attempting in the project provided.

**Comment by Tbaut** [comment]
Do you have a link to your project so that I see how it behaved here?

**Comment by jacogr** [comment]
Can push it up.

**Comment by jacogr** [comment]
Here we go https://github.com/jacogr/wasm-test-315 (Just a stock-standard Metro app... after a day of reading various blogs...)

**Comment by Tbaut** [comment]
Thanks, I was able to run your project successfully, and adapt my test project so that it works as well. I'll try to see exactly what was the trigger, but I did the following:
- eject
- place the import initOnlyWasm on the index.js
- get rid of `@polkadot/util`
- change the order of the resolver and add the transformer in `metro.config.js`. Believe it or not, if the resolver doesn't list the extensions in the same order, it fails :man_shrugging: 
- adapt the tsconfig.js

I'll go back to https://github.com/polkadot-js/common/issues/1440 in the next days now.

**Comment by jacogr** [comment]
The import does work on App as well, it just needs to be first. Seems like the resolution order is the issue. (The eject should not be needed at all)

I adapted the above to use wasm-waitReady to try and follow your problem. Originally just had the cryptoWaitReady.
